from gluon import current

fbdb = DAL("mongodb://localhost/brt", adapter_args=dict(foreign_keys=False), db_codec='UTF-8',pool_size=20)
fbdb.define_table('people',
    Field('uid','string',unique=True),
    Field('name'),
    Field('first_name'),
    Field('last_name'),
    Field('age_range'),
    Field('education'),
    Field('work'),
    Field('age_range'),
    Field('link'),
    Field('gender', 'string'),
    Field('hometown'),
    Field('location'),
    Field('picture'),
    Field('updated_time'),
    Field('locale'),
    Field('religion'),
    Field('website'),
    Field('relationship_status'),
    Field('birthday'),
    Field('timezone'),
    Field('email'),
    Field('like_count', 'integer'),
    Field('b_like_count', 'integer'),
    Field('g_like_count', 'integer'),
    Field('liked_count', 'integer'),
    Field('b_liked_count', 'integer'),
    Field('g_liked_count', 'integer'),
    Field('comment_count', 'integer'),
    Field('b_comment_count', 'integer'),
    Field('g_comment_count', 'integer'),
    Field('commented_count', 'integer'),
    Field('b_commented_count', 'integer'),
    Field('g_commented_count', 'integer'),
    Field('shared_count', 'integer'),
    Field('b_shared_count', 'integer'),
    Field('g_shared_count', 'integer'),
    Field('share_links', 'list:string'),
    Field('b_share_links', 'list:string'),
    Field('g_share_links', 'list:string'),
    Field('wordcloud', 'json'),
    Field('b_wordclouds', 'json'),
    Field('g_wordclouds', 'json'),
    Field('updated_time' , 'datetime'),
    Field('category', 'string')
    
)



fbdb.define_table('page',
    Field('fid', 'string', unique=True),
    Field('about', 'string'),
    Field('attire', 'string'),
    Field('band_members', 'string'),
    Field('best_page', 'text'),
    Field('birthday', 'string'),
    Field('booking_agent', 'string'),
    Field('can_post', 'boolean'),
    Field('category', 'string'),
    Field('category_list', 'text'),
    Field('checkins', 'integer'),
    Field('company_overview', 'string'),
    Field('cover_id', 'string'),
    Field('cover_source', 'string'),
    Field('cover_offset_y', 'integer'),
    Field('cover_offset_x', 'integer'),
    Field('current_location', 'string'),
    Field('description', 'string'),
    Field('directed_by', 'string'),
    Field('founded', 'string'),
    Field('general_info', 'string'),
    Field('general_manager', 'string'),
    Field('hometown', 'string'),
    Field('hours', 'text'),
    Field('is_permanently_closed', 'boolean'),
    Field('is_published', 'boolean'),
    Field('is_unclaimed', 'boolean'),
    Field('likes', 'integer'),
    Field('link', 'string'),
    Field('country', 'string'),
    Field('city', 'string'),
    Field('longitude', 'double'),
    Field('zip', 'string'),
    Field('state', 'string'),
    Field('street', 'string'),
    Field('located_in', 'string'),
    Field('latitude', 'double'),
    Field('mission', 'string'),
    Field('name', 'string'),
    Field('picture', 'string'),
    Field('parking_street', 'integer'),
    Field('parking_lot', 'integer'),
    Field('parking_valet', 'integer'),
    Field('phone', 'string'),
    Field('press_contact', 'string'),
    Field('price_range', 'text'),
    Field('products', 'string'),
    Field('services_kids', 'integer'),
    Field('services_delivery', 'integer'),
    Field('services_walkins', 'integer'),
    Field('services_catering', 'integer'),
    Field('services_reserve', 'integer'),
    Field('services_groups', 'integer'),
    Field('services_waiter', 'integer'),
    Field('services_outdoor', 'integer'),
    Field('services_takeout', 'integer'),
    Field('specialties_coffee', 'integer'),
    Field('specialties_drinks', 'integer'),
    Field('specialties_breakfast', 'integer'),
    Field('specialties_dinner', 'integer'),
    Field('specialties_lunch', 'integer'),
    Field('talking_about_count', 'integer'),
    Field('username', 'string'),
    Field('website', 'string'),
    Field('were_here_count', 'integer'),
    Field('updated_time_utc', 'datetime'), 
    Field('updated_time_tw', 'datetime')
)

fbdb.define_table('page_social_counts', 
    Field('fid'),
    Field('checkins','integer'),
    Field('likes','integer'),
    Field('were_here_count','integer'),
    Field('talking_about_count','integer'), 
    Field('updated_time_utc', 'datetime'), 
    Field('updated_time_tw', 'datetime')
)

fbdb.define_table('page_insights', 
    Field('fid'), 
    Field('lifetime_likes', 'json'), 
    Field('daily_people_talking', 'json'), 
    Field('weekly_people_talking', 'json'), 
    Field('days28_people_talking', 'json'), 
    Field('daily_shares_count','integer'),
    Field('daily_likes_count','integer'),
    Field('daily_comment_count','integer'),
    Field('total_comment_count','integer'),
    Field('total_shares_count','integer'),
    Field('total_likes_count','integer'),
    Field('end_time'), 
    Field('location_insights'),
    Field('end_time_utc', 'datetime'), 
    Field('end_time_tw', 'datetime')
)

fbdb.define_table('event',
    Field('fid', 'string', unique=True),
    Field('cover_id', 'string'),
    Field('cover_source', 'string'),
    Field('cover_offset_y', 'integer'),
    Field('cover_offset_x', 'integer'),
    Field('description', 'string'),
    Field('end_time', 'string'),
    Field('is_date_only', 'boolean'),
    Field('location', 'string'),
    Field('name', 'string'),
    Field('owner_id', 'string'),
    Field('owner_name', 'string'),
    Field('parent_group', 'text'),
    Field('privacy', 'string'),
    Field('start_time', 'datetime'),
    Field('ticket_uri', 'string'),
    Field('timezone', 'string'),
    Field('updated_time', 'datetime'),
    Field('venue_id', 'string'),
    Field('street', 'string'),
    Field('city', 'string'),
    Field('state', 'string'),
    Field('country', 'string'),
    Field('zip', 'string'),
    Field('located_in', 'string'),
    Field('longitude', 'double'),
    Field('latitude', 'double'),
    Field('attending', 'integer'),
    Field('declined', 'integer'),
    Field('invited', 'integer'),
    Field('maybe', 'integer'),
    Field('noreply', 'integer'),
    Field('picture_url', 'string'),
    Field('picture_is_silhouette', 'boolean'),
    Field('photos', 'text'),
    Field('videos', 'text'),
)


fbdb.define_table('post',
    Field('fid', 'string', unique=True),
    Field('application', 'string'),
    Field('caption', 'string'),
    Field('created_time', 'datetime'),
    Field('description', 'string'),
    Field('from_id', 'string'),
    Field('from_name', 'string'),
    Field('from_picture', 'string'),
    Field('icon', 'string'),
    Field('is_hidden', 'boolean'),
    Field('link', 'string'),
    Field('message', 'string'),
    Field('message_tags', 'text'),
    Field('link_name', 'string'),
    Field('object_id', 'string'),
    Field('picture', 'string'),
    Field('placeid', 'string'),
    Field('placename', 'string'),
    Field('street', 'string'),
    Field('city', 'string'),
    Field('state', 'string'),
    Field('country', 'string'),
    Field('zip', 'string'),
    Field('located_in', 'string'),
    Field('longitude', 'double'),
    Field('latitude', 'double'),
    Field('privacy_description', 'string'),
    Field('privacy_value', 'text'),
    Field('privacy_friends', 'text'),
    Field('privacy_allow', 'text'),
    Field('privacy_deny', 'text'),
    Field('properties', 'text'),
    Field('shares_count', 'integer'),
    Field('likes', 'json'),
    Field('likes_count', 'integer'),
    Field('comment_count', 'integer'),
    Field('comments_arr', 'json'),
    Field('source', 'string'),
    Field('status_type', 'string'),
    Field('story', 'string'),
    Field('to', 'text'),
    Field('ptype', 'string'),
    Field('updated_time', 'datetime'),
    Field('with_tags', 'text'),
    Field('team')
)

fbdb.define_table('post_counts', 
    Field('fid', 'string'), 
    Field('from_id', 'string'),
    Field('date_time', 'datetime'), 
    Field('shares_count','integer'), 
    Field('updated_time', 'datetime'), 
    Field('likes_count','integer'), 
    Field('comment_count','integer'),
    Field('updated_time_tw', 'datetime'), 
    Field('updated_time_utc', 'datetime')
)



fbdb.define_table('wholikes',
    Field('Object_id', 'string'),
    Field('fid', 'string'),
    Field('name', 'string')
)


fbdb.define_table('comments',
    Field('object_id', 'string'),
    Field('fid', 'string',unique=True),
    Field('from_id', 'string'),
    Field('from_name', 'string'),
    Field('picture', 'string'),
    Field('message', 'string'),
    Field('can_remove', 'string'),
    Field('created_time', 'datetime'),
    Field('likes', 'json', default={}),
    Field('like_count', 'integer'),
    Field('comments', 'json', default={}),
    Field('comment_count', 'integer'),
    Field('user_likes', 'boolean'),
    Field('share_count', 'integer'),
    Field('parent', 'json'),
    Field('from_page'),
    Field('from_team'),
    Field('from_post'),
    Field('segment')
)

fbdb.define_table('news',
    Field('fid', 'string'),
    Field('created_time', 'datetime'),
    Field('updated_time', 'datetime'),
    Field('share_count', 'integer'),
    Field('comment_count', 'integer'),
    Field('created_time', 'datetime'),
    Field('date_time', 'datetime'),
    Field('source', 'string'),
    Field('summary', 'string'),
    Field('title', 'string'),
    Field('href', 'string', unique=True),
    Field('fb_url', 'string', unique=True),
    Field('photo', 'string'),
    Field('related_news' , 'json', default=[]),
    Field('related_news_date_time', default=[]),
    Field('updated_time_tw', 'datetime'),
    Field('updated_time_utc', 'datetime'),
    Field('from_team'),
    Field('related_news_source','json', default=[])
)

fbdb.news.href.requires = IS_URL()

fbdb.define_table('news_comments',
    Field('fid', 'string',unique=True),
    Field('from_id', 'string'),
    Field('from_name', 'string'),
    Field('message', 'string'),
    Field('can_remove', 'string'),
    Field('created_time', 'datetime'),
    Field('likes', 'json', default={}),
    Field('like_count', 'integer'),
    Field('from_team'),
    Field('comments', 'json', default={}),
    Field('parent', 'json'),
    Field('segment'),
    Field('news_source'),
    Field('news_href'),
    Field('news_fid')
)

fbdb.define_table('news_social_counts', 
    Field('fid'),
    Field('news_href'),
    Field('comment_count','integer'),
    Field('share_count','integer'),
    Field('updated_time_utc', 'datetime'),
    Field('news_source'),
    Field('updated_time_tw', 'datetime')
)


fbdb.define_table('wordcloud',
    Field('wordclouds', 'json'),
    Field('b_wordclouds', 'json'),
    Field('g_wordclouds', 'json'),
    Field('comment_count', 'integer'),
    Field('b_comment_count', 'integer'),
    Field('g_comment_count', 'integer'),
    Field('female_comment_count', 'integer'),
    Field('male_comment_count', 'integer'),
    Field('female_wordclouds' , 'json'),
    Field('male_wordclouds' , 'json'),
    Field('updated_time' , 'datetime')
)

fbdb.define_table('top_likes',
    Field('top_likes', 'json'),
    Field('updated_time' , 'datetime')
)


fbdb.define_table('mentions',
    Field('qstring', 'string'),
    Field('comment_arr', 'json'),
    Field('b_comment_arr', 'json'),
    Field('g_comment_arr', 'json'),
    Field('comment_count', 'integer'),
    Field('b_comment_count', 'integer'),
    Field('g_comment_count', 'integer'),
    Field('user_count', 'integer'),
    Field('b_user_count', 'integer'),
    Field('g_user_count', 'integer'),
    Field('male_user_count', 'integer'),
    Field('female_user_count', 'integer'),
    Field('male_comment_arr', 'json'),
    Field('female_comment_arr', 'json'),
    Field('stat', 'json'),
    Field('wordcloud', 'json'),
    Field('female_wordcloud', 'json'),
    Field('male_wordcloud', 'json'),
    Field('b_wordcloud', 'json'),
    Field('g_wordcloud', 'json'),
    Field('updated_time' , 'datetime')
)



fbdb.define_table('pcolor',
    Field('date_time', 'datetime', default=request.now),
    Field('result', 'json')
)



fbdb.define_table('graphAPI_Error',
    Field('oid'),
    Field('date_time', 'datetime', default=request.now),
    Field('code'),Field('error_msg')
)


fbdb.define_table('friends',
    Field('uid','string'),
    Field('name'),
    Field('color', 'integer'),
    Field('first_name'),
    Field('last_name'),
    Field('age_range'),
    Field('education' , 'json'),
    Field('work', 'json'),
    Field('age_range'),
    Field('link'),
    Field('gender', 'string'),
    Field('hometown' , 'json'),
    Field('location', 'json'),
    Field('likes', 'json'),
    Field('picture'),
    Field('updated_time'),
    Field('locale'),
    Field('religion'),
    Field('website'),
    Field('relationship_status'),
    Field('birthday'),
    Field('timezone'),
    Field('email'),
    Field('like_count', 'integer'),
    Field('b_like_count', 'integer'),
    Field('g_like_count', 'integer'),
    Field('comment_count', 'integer'),
    Field('b_comment_count', 'integer'),
    Field('g_comment_count', 'integer'),
    Field('share_count', 'integer'),
    Field('b_share_count', 'integer'),
    Field('g_share_count', 'integer'),
    Field('share_links', 'list:string'),
    Field('b_share_links', 'list:string'),
    Field('g_share_links', 'list:string'),
    Field('wordcloud', 'json'),
    Field('b_wordclouds', 'json'),
    Field('g_wordclouds', 'json'),
    Field('updated_time' , 'datetime')
    
)

fbdb.define_table('politician',
    Field('fid', 'string', unique=True),
    Field('name', 'string'),
    Field('party', 'json'),
    Field('username', 'string'),
    Field('about', 'string'),
    Field('attire', 'string'),
    Field('band_members', 'string'),
    Field('best_page', 'text'),
    Field('birthday', 'string'),
    Field('booking_agent', 'string'),
    Field('can_post', 'boolean'),
    Field('category', 'string'),
    Field('category_list', 'text'),
    Field('checkins', 'integer'),
    Field('company_overview', 'string'),
    Field('cover_id', 'string'),
    Field('cover_source', 'string'),
    Field('cover_offset_y', 'integer'),
    Field('cover_offset_x', 'integer'),
    Field('current_location', 'string'),
    Field('description', 'string'),
    Field('directed_by', 'string'),
    Field('founded', 'string'),
    Field('general_info', 'string'),
    Field('general_manager', 'string'),
    Field('hometown', 'string'),
    Field('hours', 'text'),
    Field('is_permanently_closed', 'boolean'),
    Field('is_published', 'boolean'),
    Field('is_unclaimed', 'boolean'),
    Field('likes', 'integer'),
    Field('link', 'string'),
    Field('country', 'string'),
    Field('city', 'string'),
    Field('longitude', 'double'),
    Field('zip', 'string'),
    Field('state', 'string'),
    Field('street', 'string'),
    Field('locale', 'string'),
    Field('located_in', 'string'),
    Field('latitude', 'double'),
    Field('mission', 'string'),
    Field('parking_street', 'integer'),
    Field('parking_lot', 'integer'),
    Field('parking_valet', 'integer'),
    Field('phone', 'string'),
    Field('press_contact', 'string'),
    Field('price_range', 'text'),
    Field('products', 'string'),
    Field('services_kids', 'integer'),
    Field('services_delivery', 'integer'),
    Field('services_walkins', 'integer'),
    Field('services_catering', 'integer'),
    Field('services_reserve', 'integer'),
    Field('services_groups', 'integer'),
    Field('services_waiter', 'integer'),
    Field('services_outdoor', 'integer'),
    Field('services_takeout', 'integer'),
    Field('specialties_coffee', 'integer'),
    Field('specialties_drinks', 'integer'),
    Field('specialties_breakfast', 'integer'),
    Field('specialties_dinner', 'integer'),
    Field('specialties_lunch', 'integer'),
    Field('talking_about_count', 'integer'),
    Field('website', 'string'),
    Field('were_here_count', 'integer'),
    Field('updated_time' , 'datetime')
)

fbdb.define_table('event_logs',
    Field('function', 'string'),
    Field('started_time' , 'datetime'),
    Field('ended_time' , 'datetime'),
)
